-- ─────────────────────────────────────────────────────────────────────────────
-- Telemetry — how each host's app is behaving
--
-- Written by the app, readable only by platform admins. Deliberately carries
-- NO guest data: names, notes and rates never leave the host's own tables.
-- ─────────────────────────────────────────────────────────────────────────────

create table public.app_sessions (
  id            uuid primary key,                  -- generated by the client
  host_id       uuid references public.hosts on delete set null,
  user_id       uuid references auth.users on delete set null,
  app_version   text,
  user_agent    text,
  started_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now()
);

create table public.app_events (
  id           bigserial primary key,
  session_id   uuid,
  host_id      uuid references public.hosts on delete set null,
  user_id      uuid references auth.users on delete set null,
  name         text not null,                      -- screen_view | booking_created …
  props        jsonb not null default '{}'::jsonb, -- counts and ids only, never PII
  app_version  text,
  created_at   timestamptz not null default now()
);

create table public.app_errors (
  id           bigserial primary key,
  session_id   uuid,
  host_id      uuid references public.hosts on delete set null,
  user_id      uuid references auth.users on delete set null,
  message      text not null,
  stack        text,
  source       text,
  line         int,
  col          int,
  app_version  text,
  user_agent   text,
  created_at   timestamptz not null default now()
);

create index app_events_host_time_idx on public.app_events (host_id, created_at desc);
create index app_events_name_idx      on public.app_events (name, created_at desc);
create index app_errors_host_time_idx on public.app_errors (host_id, created_at desc);
create index app_errors_msg_idx       on public.app_errors (message, created_at desc);
